apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-app
  namespace: flux-system
spec:
  targetNamespace: sample-app-flux
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: ./sample-app
      sourceRef:
        kind: GitRepository
        name: sample-app
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2