apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: sample-app
  namespace: flux-system
spec:
  targetNamespace: sample-app-flux
  interval: 5m
  chart: ./sample-app
  reconcileStrategy: Revision 
  sourceRef:
    kind: GitRepository
    name: sample-app