apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: sample-app
  namespace: flux-system
spec:
  targetNamespace: sample-app-flux
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: "./sample-app"
      reconcileStrategy: Revision 
      interval: 1m     
      sourceRef:
        kind: GitRepository
        name: sample-app