project: sample-app
source:
  repoURL: 'https://github.com/Kulivox/dt-sample-helm-chart.git'
  path: sample-app
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: sample-app
syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
