apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-bootstrap
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: App used to automatically create cluster apps on push
  destinations:
    - name: in-cluster
      namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/Kulivox/dt-sample-helm-chart.git'
status: {}