apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-app
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: This is just an example.
  destinations:
    - name: in-cluster
      namespace: sample-app
      server: 'https://kubernetes.default.svc/'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/Kulivox/dt-sample-helm-chart.git'
status: {}